cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5440.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5440.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_7183.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_7183.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_6666.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_6666.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_6643.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_6643.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_8917.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_8917.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5561.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5561.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5823.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5823.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_8153.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_8153.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_7187.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_7187.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5736.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5736.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5478.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5478.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_7477.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_7477.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5764.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5764.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_8939.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_8939.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5759.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5759.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_8519.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_8519.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_8038.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_8038.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_8957.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_8957.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_6357.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_6357.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_6289.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_6289.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_9191.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_9191.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_6552.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_6552.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_7369.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_7369.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_5173.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_5173.nii.gz
cp /scratch/kderaad/Ergo_Res4/masks/combined_bone_mask_7860.nii.gz /scratch/kderaad/Ergo_Res4_N4BC/masks/combined_bone_mask_7860.nii.gz
